### ISSUE TITLE
Seems to be incompatible with "Better Smithing Table" mod

### ISSUE THREAD

**Issue by tuguzD** [Andrew6rant/Deluxe-Smithing#1]
With both mods installed:

- [Deluxe Smithing](https://github.com/Andrew6rant/Deluxe-Smithing) from [Andrew6rant](https://github.com/Andrew6rant)
- and [Better Smithing Table](https://github.com/jjblock21/BetterSmithingTable) from [jjblock21](https://github.com/jjblock21),

it keeps crashing my game right after opening Smithing Table's UI.

Log is here: [latest.log](https://github.com/Andrew6rant/Deluxe-Smithing/files/13168811/latest.log)

**Comment by Andrew6rant** [comment]
looks like both our mods redirect at the same point. Simple fix.

https://github.com/Andrew6rant/Deluxe-Smithing/assets/57331134/b2f7ff87-f264-430e-b753-3e13e0c6b24b

If you want the armor stand to be centered properly with that mod installed, use the following config values:

```json
{
  "armorStandRenderX": 111,
  "armorStandRenderY": 67,
  "armorStandRenderSize": 25,
  [...] (anything)
}
```
